### ISSUE TITLE
Diagnostic notation to support trailing commas

### ISSUE THREAD

**Issue by jnz86** [cbor-wg/edn-literal#5]
This is low on any list of priorities, but when working with C, dart, rust, python, etc, trailing commas are allowed and it's handy to have slightly looser rules where no real damage could come from the mistake.

If CBOR inherited an inability to accept a trailing comma from JSON, I question the usefulness of it. 

I would think this needs some consideration because it would be making a version incompatibility in existing parsers, but it is something I would like to see happen.

**Comment by chrysn** [comment]
I'd appreciate if we could make this happen -- EDN is often hand-written, and hand-writing these days means having an editor that can copy and adjust lines, and having a trialing comma in a multi-line expression is quite helpful to avoid tedious editing.

(Plus it makes diffs so much more readable.)
