### ISSUE TITLE
Normative appendix in non-normative document

### ISSUE THREAD

**Issue by chrysn** [cbor-wg/edn-literal#52]
This issue was brought up in [today's interim](https://datatracker.ietf.org/meeting/interim-2024-cbor-11/session/cbor), with a note to have another look at it:

This document is an informative document (on grounds of not being an interchange format, and thus not having the strict versioning and no-breakage requirements CBOR itself has). Still, the appendix states that it is normative.

A phrasing that was used in the meeting was (roughly, and composing two statements)( "For users who choose this format, this ABNF normatively describes valid data items. There is no requirement to use exactly this ABNF rule set: other ABNF rules or grammars can express the same validity constraints."

**Comment by cabo** [comment]
Dividing an informational document into normative and informative parts is OK if the document defines a protocol.

EDN definitely is a protocol, so I think there is no contradiction here at all.

(There are lots of specifications that are informational; suddenly no longer being able to have informative and normative parts of such a specification would be a major regression.)
