### ISSUE TITLE
Document floating point values vs. integer numbers

### ISSUE THREAD

**Issue by cabo** [cbor-wg/edn-literal#6]
EDN implementations use the wide-spread convention to use NR2/NR3 syntax to notate floating point values and only NR1 to notate integer values; RFC 8949 uses this convention in Appendix A without explaining it in its Section 8 — an omission that needs to be addressed here.

**Comment by chrysn** [comment]
Not sure I understand "NR2/NR3" syntax (thought it'd be a term from the [JSON RFC](https://www.rfc-editor.org/rfc/rfc8259) but it's not) -- am I right in mapping this to the concern that any number of `[minus] int` ABNF shape is an integer, and the occurrence of any frac or exp (even 0) makes it a float?

**Comment by cabo** [comment]
In <https://mailarchive.ietf.org/arch/msg/json/8o-MsWsF5FA7ShZg1Q-IZM6sNB0>
I wrote:

> There actually is a standard that should be referenced: ISO 6093:1985 (*), with its subformats NR1, NR2, and NR3.
> (*) Yes, this standard has not been touched since 1985.  It is still on the books as an effective ISO standard.

Joe has pointed out that my usage of the terms from 1985 maybe wasn't quite correct.
What I wanted to say was indeed: ignoring the initial minus, decimal digits ➔ integer, decimal digits + dot and/or exponent ➔ float.  RFC 8610 says this in its Section 2.2.1, but EDN doesn't.

**Comment by cabo** [comment]
Fixed in b8de58b
