### ISSUE TITLE
Comments containing slashes ➔ end-of-line comments

### ISSUE THREAD

**Issue by chrysn** [cbor-wg/edn-literal#8]
Given that the box has been opened to collect (E)DN feature requests here, there's one I'd like to propose: Allow slashes in comments.

Our current comments span from one `/` to the next, so while a comment like `/ see http://example.com for details /` technically works, that is just because luckily there are not odd slashes in the URI. Some examples already contain weird workarounds that substitute slashes in the comment with weird lookalike characters, breaking copy-paste of the URI (`/ See http:⁄⁄example.com⁄ /`).

One way of achieving this is to count asterisks immediately following the first slash, and requiring (at least) the same number of asterisks before the trailing slash. Thus, `/ comment /`, `/* See http://example.com/ */` and `/** You can wrap comments in /* slashes */ if needed **/` would all be single closed comments.

Noteworthy properties of this proposal:
* +: Mostly backward compatible: Documents valid under the old rules are still valid unless they had asterisks immediately around their slashes.
* +: Looks like C comments. If people *did* use asterisk around comments previously, it's likely they did it C style out of habit, thus not breaking things.
* +: Allows nested comments. If you have a section that contains comments and want to comment out the whole section, you just pick one more asterisk than the comments in there use.
* –: Users in the habits of Doxygen might be tripped up, because Doxygen distinguishes regular C comments `/* comment */` from Doxygen comments `/** @directive */` that don't necessarily have the double asterisk on their trailing end. Catering for those habits would mean losing the nesting property, unless we want to start counting comment depths (which would again be unlike what C does).

**Comment by cabo** [comment]
I think we are more likely to add line-end comments (whether we start them with `#` and/or `;` and/or even `//`, you can use as many slashes there as you like).

**Comment by chrysn** [comment]
Only if I can do the asterisk part with "regular" expressions instead of ABNF ;-)

More seriously: Introducing trailing comments would solve the issue almost just as well.

**Comment by cabo** [comment]
OK, so this is "almost solved" now by c4aff27
